---
# -v - verbose output
# -K for password for become user - needed on my localhost but not for VMs
# run with: ansible-playbook provision-local-or-VM.yml -i inventory-local -v -K
# OR ansible-playbook provision-local-or-VM.yml -i inventory-VM1-tester -i inventory-VM2-app
# OR ansible-playbook provision-local-or-VM.yml -i inventory-VM2-tester -i inventory-VM2-app
# depending on environment we want to build

- name: setup JMeter on tester
  hosts: tester
  tasks:
    - name: create JMeter install directory
      ansible.builtin.file:
        path: "{{install_dir}}/jmeter"
        state: directory
        owner: "{{permissions_owner}}"
        group: "{{permissions_group}}"
        mode: '0777'
    - name: copy enhanced Jmeter into install directory
      ansible.builtin.copy:
        src: install-resources/apache-jmeter-5.4.1-enhanced.tar.gz
        dest: "{{install_dir}}/jmeter"
        owner: "{{permissions_owner}}"
        group: "{{permissions_group}}"
        mode: '0777'
    - name: unarchive enhanced Jmeter into install directory
      ansible.builtin.unarchive:
        src: "{{install_dir}}/jmeter/apache-jmeter-5.4.1-enhanced.tar.gz"
        dest: "{{install_dir}}/jmeter"
        remote_src: yes
        owner: "{{permissions_owner}}"
        group: "{{permissions_group}}"
        mode: '0777'

    - name: create Maven install directory
      ansible.builtin.file:
        path: "{{install_dir}}/maven"
        state: directory
        owner: "{{permissions_owner}}"
        group: "{{permissions_group}}"
        mode: '0777'
    - name: Download maven version 3.8.2
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz
        dest: "{{install_dir}}/maven/apache-maven-3.8.2-bin.tar.gz"
        mode: '0777'
    - name: unarchive Maven
      ansible.builtin.unarchive:
        src: "{{install_dir}}/maven/apache-maven-3.8.2-bin.tar.gz"
        dest: "{{install_dir}}/maven"
        remote_src: yes
        owner: "{{permissions_owner}}"
        group: "{{permissions_group}}"
        mode: '0777'

    - name: Git install
      become: yes
      ansible.builtin.yum:
        name: git
        state: present

    - name: Benchmark clone
      ansible.builtin.git:
        repo: 'https://github.com/RHEcosystemAppEng/kogito-benchmark.git'
        dest: "{{install_dir}}/kogito-benchmark"
    - name: set JMeter Home directory
      ansible.builtin.copy:
        dest: "{{install_dir}}/kogito-benchmark/test-clients/jmeter-client/jmeterHome.txt"
        content: "{{install_dir}}/jmeter/apache-jmeter-5.4.1"    
# todo : add the symbolic link to mvn
# todo: install java

# for app host: a) also do all tester host stuff + disable firewall, do docker install
