---
- name: remove mongo container if present
  containers.podman.podman_container:
    name: kogito-mongodb
    image: quay.io/dmartino/mongo:4.4.9
    state: absent
    ports:
      - "27017:27017"

- name: Start a mongo container
  containers.podman.podman_container:
    name: kogito-mongodb
    image: quay.io/dmartino/mongo:4.4.9
    state: started
    ports:
      - "27017:27017"
  when: test_defs.AppInfra.Mongo == "yes" and reqRoleAction == "setup"